import { Pool } from 'pg';
import { SupplierProfile } from '../types/auth';

/**
 * Supplier profile repository for database operations
 */
export class SupplierRepository {
  constructor(private pool: Pool) {}

  /**
   * Find supplier profile by user ID
   * @param userId - User ID
   * @returns SupplierProfile object or null if not found
   */
  async findByUserId(userId: string): Promise<SupplierProfile | null> {
    const result = await this.pool.query(
      'SELECT id_supplier_profile, user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel, created_at, updated_at FROM supplier_profiles WHERE user_id = $1',
      [userId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return result.rows[0];
  }

  /**
   * Find supplier profile by ID
   * @param id - Supplier profile ID
   * @returns SupplierProfile object or null if not found
   */
  async findById(id: string): Promise<SupplierProfile | null> {
    const result = await this.pool.query(
      'SELECT id_supplier_profile, user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel, created_at, updated_at FROM supplier_profiles WHERE id_supplier_profile = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return result.rows[0];
  }

  /**
   * Create a new supplier profile
   * @param supplierData - Supplier profile data (id_supplier_profile, created_at, updated_at will be generated by DB)
   * @returns Created supplier profile object
   */
  async create(supplierData: Omit<SupplierProfile, 'id_supplier_profile' | 'created_at' | 'updated_at'>): Promise<SupplierProfile> {
    const result = await this.pool.query(
      `INSERT INTO supplier_profiles (user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel) 
       VALUES ($1, $2, $3, $4, $5, $6) 
       RETURNING id_supplier_profile, user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel, created_at, updated_at`,
      [
        supplierData.user_id,
        supplierData.description,
        supplierData.identifiant_professionnel,
        supplierData.statut_verification,
        supplierData.date_verification,
        supplierData.email_professionnel
      ]
    );
    
    return result.rows[0];
  }

  /**
   * Update supplier profile by user ID
   * @param userId - User ID
   * @param supplierData - Supplier profile data to update
   * @returns Updated supplier profile object or null if not found
   */
  async updateByUserId(userId: string, supplierData: Partial<Omit<SupplierProfile, 'id_supplier_profile' | 'user_id' | 'created_at' | 'updated_at'>>): Promise<SupplierProfile | null> {
    // Build dynamic update query
    const fields = [];
    const values: any[] = [];
    let index = 1;

    if (supplierData.description !== undefined) {
      fields.push(`description = $${index++}`);
      values.push(supplierData.description);
    }
    if (supplierData.identifiant_professionnel !== undefined) {
      fields.push(`identifiant_professionnel = $${index++}`);
      values.push(supplierData.identifiant_professionnel);
    }
    if (supplierData.statut_verification !== undefined) {
      fields.push(`statut_verification = $${index++}`);
      values.push(supplierData.statut_verification);
    }
    if (supplierData.date_verification !== undefined) {
      fields.push(`date_verification = $${index++}`);
      values.push(supplierData.date_verification);
    }
    if (supplierData.email_professionnel !== undefined) {
      fields.push(`email_professionnel = $${index++}`);
      values.push(supplierData.email_professionnel);
    }

    if (fields.length === 0) {
      // No fields to update
      return await this.findByUserId(userId);
    }

    values.push(userId); // for WHERE clause

    const result = await this.pool.query(
      `UPDATE supplier_profiles SET ${fields.join(', ')} WHERE user_id = $${index} 
       RETURNING id_supplier_profile, user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel, created_at, updated_at`,
      values
    );
    
    if (result.rows.length === 0) {
      return null;
    }

    return result.rows[0];
  }

  /**
   * Find supplier profiles with pagination and search
   * @param page - Page number (default: 1)
   * @param limit - Items per page (default: 10)
   * @param search - Search term for identifiant_professionnel, description, email_professionnel
   * @returns Paginated list of supplier profiles
   */
  async findAll(page: number = 1, limit: number = 10, search: string = ''): Promise<{ profiles: SupplierProfile[]; total: number; page: number; limit: number; totalPages: number }> {
    // Build search condition
    let searchCondition = '';
    const searchValues: any[] = [];
    let searchIndex = 1;

    if (search.trim() !== '') {
      searchCondition = `WHERE (identifiant_professionnel ILIKE $${searchIndex++} OR description ILIKE $${searchIndex++} OR email_professionnel ILIKE $${searchIndex++}) AND `;
      const searchTerm = `%${search}%`;
      searchValues.push(searchTerm, searchTerm, searchTerm);
    }

    // Count total records
    const countResult = await this.pool.query(
      `SELECT COUNT(*) as total FROM supplier_profiles ${searchCondition}true`,
      [...searchValues]
    );
    const total = parseInt(countResult.rows[0].total);
    const totalPages = Math.ceil(total / limit);

    // Ensure page is within bounds
    const safePage = Math.max(1, Math.min(page, totalPages || 1));
    const offset = (safePage - 1) * limit;

    // Get paginated records
    const result = await this.pool.query(
      `SELECT id_supplier_profile, user_id, description, identifiant_professionnel, statut_verification, date_verification, email_professionnel, created_at, updated_at
       FROM supplier_profiles ${searchCondition}true
       ORDER BY created_at DESC
       LIMIT $${searchIndex + (searchCondition === '' ? 1 : 2)} OFFSET $${searchIndex + (searchCondition === '' ? 2 : 3)}`,
      [
        ...searchValues,
        limit,
        offset
      ]
    );

    return {
      profiles: result.rows,
      total,
      page: safePage,
      limit,
      totalPages
    };
  }
}
