import { Pool } from 'pg';
import { User } from '../types/auth';

/**
 * User repository for database operations
 */
export class UserRepository {
  constructor(private pool: Pool) {}

  /**
   * Find user by email
   * @param email - User email
   * @returns User object or null if not found
   */
  async findByEmail(email: string): Promise<User | null> {
    const result = await this.pool.query(
      'SELECT id_user, email, password_hash, role, nom_entreprise, telephone, created_at, updated_at FROM users WHERE email = $1',
      [email]
    );
    
    if (result.rows.length === 0) {
      return null;
    }
    
    return result.rows[0];
  }

  /**
   * Find user by ID
   * @param id - User ID
   * @returns User object or null if not found
   */
  async findById(id: string): Promise<User | null> {
    const result = await this.pool.query(
      'SELECT id_user, email, password_hash, role, nom_entreprise, telephone, created_at, updated_at FROM users WHERE id_user = $1',
      [id]
    );
    
    if (result.rows.length === 0) {
      return null;
    }
    
    return result.rows[0];
  }

  /**
   * Create a new user
   * @param userData - User data to insert (id_user, created_at, updated_at will be generated by DB)
   * @returns Created user object
   */
  async create(userData: Omit<User, 'id_user' | 'created_at' | 'updated_at'>): Promise<User> {
    const result = await this.pool.query(
      `INSERT INTO users (email, password_hash, role, nom_entreprise, telephone) 
       VALUES ($1, $2, $3, $4, $5) 
       RETURNING id_user, email, password_hash, role, nom_entreprise, telephone, created_at, updated_at`,
      [
        userData.email,
        userData.password_hash,
        userData.role,
        userData.nom_entreprise,
        userData.telephone
      ]
    );
    
    return result.rows[0];
  }
}
